// Global configuration
export const GEMINI_MODEL_ID = "gemini-2.5-flash-preview-09-2025";

export const API_KEYS = {
    ADTMC: "$KEY_ADTMC",
    CARDIOLOGY: "$KEY_CARDIOLOGY",
    IM: "$KEY_IM",
    JOURNAL_CLUB: "$KEY_JOURNAL_CLUB",
    NEUROLOGY: "$KEY_NEUROLOGY",
    ORTHOPEDICS: "$KEY_ORTHOPEDICS",
    PSYCHIATRY: "$KEY_PSYCHIATRY",
    RHEUMATOLOGY: "$KEY_RHEUMATOLOGY",
    START_PAGE: "$KEY_START_PAGE"
};
